src/main/java/students/polina_ivashkevich/lesson_2/level_2/task_8/Name.java
=> St polina ivashkevich lesson 2 level 2 task 8 

resources/lesson 2/homework/level 2 - beginner/Task_5.txt, src/main/java/students/tatjana_topchilina_lesson_2/level_2/task_3/Book.java
=> Lesson_2.level_2.task_3

src/main/java/Numbers.java
=> Lesson_2.level_1.task_1

src/main/java/tatjana_topcilina_lesson_2/level_2/task_5/BankAccount.java
=> Lesson_2.level_2.task_5

src/main/java/tatjana_topcilina_lesson_2/level_2/task_5/BankAccount.java, src/main/java/tatjana_topcilina_lesson_2/level_2/task_6/Turtle.java
=> St tatjana topcilina lesson2 level2 task6

src/main/java/tatjana_topcilina/lesson_2/level_2/task_7/LoginService.java
=> Lesson_2.level_2.task_7

src/main/java/students/jekaterina_aleksejeva/lesson_3/level_1/Robot.java, src/main/java/students/jekaterina_aleksejeva/lesson_3/level_1/RobotDemo.java
=> lesson3 leve1 3 Robots with different names

src/main/java/students/jekaterina_aleksejeva/lesson_3/level_1/Robot.java, src/main/java/students/jekaterina_aleksejeva/lesson_3/level_1/RobotDemo.java, src/main/java/students/jekaterina_aleksejeva/lesson_3/level_2/task_7/Task7.java, src/main/java/students/jekaterina_aleksejeva/lesson_3/level_2/task_8/Task8.java, src/main/java/students/jekaterina_aleksejeva/lesson_3/level_3/NewRobot.java, src/main/java/students/jekaterina_aleksejeva/lesson_3/level_3/NewRobotDemo.java
Для level 3 создала новые классы NewRobot и NewRobotDemo, чтобы дать Роботам имена согласно условиям задачи,
так как в level 1 у меня уже была попытка дать каждому свое имя. Обещаю в дальнейшем строго следовать инструкциям! :)
=> St kate aleksejeva lesson3 level3

src/main/java/students/jekaterina_aleksejeva/lesson_3/level_4/task_17/BankAccount.java, src/main/java/students/jekaterina_aleksejeva/lesson_3/level_5/task_18/Dog.java
исправила: теперь только одно свойство name.
=> St kate aleksejeva lesson3 level5 fixedtask18

src/main/java/students/jekaterina_aleksejeva/lesson_3/level_4/task_14/Book.java, src/main/java/students/jekaterina_aleksejeva/lesson_3/level_4/task_15/Phone.java, src/main/java/students/jekaterina_aleksejeva/lesson_3/level_4/task_16/Car.java, src/main/java/students/jekaterina_aleksejeva/lesson_3/level_4/task_17/BankAccount.java, src/main/java/students/jekaterina_aleksejeva/lesson_3/level_5/task_18/Dog.java, src/main/java/students/jekaterina_aleksejeva/lesson_3/level_5/task_19/Dog.java, src/main/java/students/jekaterina_aleksejeva/lesson_3/level_5/task_20/Dog.java, src/main/java/students/jekaterina_aleksejeva/lesson_3/level_5/task_20/DogDemo.java
сделала 2 отдельных класса, как требовалось изначально в level 5
=> St kate aleksejeva lesson3 level5 task20

src/main/java/students/viktors_cesnokovs/lesson_2/level_7/task_28/CamelCase.java
=> lesson 2 level 6 task 24

src/main/java/students/viktors_cesnokovs/lesson_2/level_7/task_29/SumTwoNumbers.java
Первый comit был произведен случайно )
=> St viktor cesnokov lesson2 level7 task29

src/main/java/students/viktors_cesnokovs/lesson_3/level_5/task_19/Dog.java
=> lesson 3 level 5 task 19

src/main/java/students/nikita_bobrovs/lesson_4/level_6/task_17/Stock.java
Можно ли было как нибудь реализовать updatePrice() через ArrayList? Или при данных условиях не получалось бы всё учесть?
=> Lesson 4 level 6 task 17

src/main/java/students/polina_ivashkevich/lesson_3/level_5/task_18/Dog.java, src/main/java/students/polina_ivashkevich/lesson_3/level_5/task_18/DogDemo.java
=> Lesson 3 level 5 task 18

src/main/java/students/jelena_kaverska/lesson_5/level_4/task_25/Task25.java, src/main/java/students/jelena_kaverska/lesson_5/level_4/task_26/Task26.java, src/main/java/students/jelena_kaverska/lesson_5/level_4/task_27/Task27.java, src/main/java/students/jelena_kaverska/lesson_5/level_4/task_28/Task28.java, src/main/java/students/jelena_kaverska/lesson_5/level_4/task_29/Task29.java, src/main/java/students/jelena_kaverska/lesson_5/level_4/task_30/Task30.java
Не удержалась без стримов.. getAsInt(); - нормально в этом случае (таск 27) и плохая практика всегда ?
=> Lesson 5 level 4 all tasks

src/main/java/students/jekaterina_aleksejeva/lesson_5/level_6/tasks_34_38_updated/ArrayUtil.java
отправляю все таски 34-38 из level_6 в одном обновленном файле
:)
=> lesson5 level6 tasks34-38 updated all in one

src/main/java/students/jana_sergejenko/lesson_4/level_7/task_22/FizzBuzz.java, src/main/java/students/jana_sergejenko/lesson_4/level_7/task_22/FizzBuzzTest.java, src/main/java/students/jana_sergejenko/lesson_6/level_2/task_7/DayOfTheWeekDetector.java, src/main/java/students/jana_sergejenko/lesson_6/level_2/task_7/DayOfTheWeekDetectorDemo.java, src/main/java/students/jana_sergejenko/lesson_6/level_2/task_7/DayOfTheWeekDetectorTest.java
=> lesson 6 level 2 all tasks

src/main/java/students/jelena_kaverska/lesson_6/level_5/tasks_22_26/TicTacToe.java, src/main/java/students/jelena_kaverska/lesson_6/level_6/task_27_29/TicTacToe.java, src/main/java/students/jelena_kaverska/lesson_6/level_6/task_27_29/TicTacToeTest.java
=> Lesson 6 level levels 5-6: 22-29 update

src/main/java/students/polina_ivashkevich/lesson_2/level_3/task_10/Radius.java
=> Lesson 2 level 3 task 10

src/main/java/students/polina_ivashkevich/lesson_2/level_5/task_15/Text.java, src/main/java/students/polina_ivashkevich/lesson_2/level_5/task_15/Text1.java
=> St polina ivashkevich lesson 2 level 5 task 15 1

src/main/java/students/polina_ivashkevich/lesson_3/level_7/task_31/Product.java
=> Lesson 3 level 7 task 31

src/main/java/students/jelena_kaverska/lesson_7/level_6/task_10/CreditCard.java, src/main/java/students/jelena_kaverska/lesson_7/level_6/task_10/CreditCardTest.java
Nested ifs оставила, пока не придумала, как иначе переписать
=> Lesson 7 level level 6 task 10 upd

src/main/java/students/polina_ivashkevich/lesson_2/level_2/task_8/Name.java
=> Lesson 2 level 2 task 8

src/main/java/students/jelena_kaverska/lesson_8/level_4/task_15/Shape.java, src/main/java/students/jelena_kaverska/lesson_8/level_4/task_16_17_18_19/Circle.java, src/main/java/students/jelena_kaverska/lesson_8/level_4/task_16_17_18_19/CircleTests.java, src/main/java/students/jelena_kaverska/lesson_8/level_4/task_16_17_18_19/Rectangle.java, src/main/java/students/jelena_kaverska/lesson_8/level_4/task_16_17_18_19/RectangleTests.java, src/main/java/students/jelena_kaverska/lesson_8/level_4/task_16_17_18_19/Shape.java, src/main/java/students/jelena_kaverska/lesson_8/level_4/task_16_17_18_19/Square.java, src/main/java/students/jelena_kaverska/lesson_8/level_4/task_16_17_18_19/SquareTests.java, src/main/java/students/jelena_kaverska/lesson_8/level_4/task_16_17_18_19/Triangle.java, src/main/java/students/jelena_kaverska/lesson_8/level_4/task_16_17_18_19/TriangleTests.java
В таск 15 по задаче у Shape есть свойство 
private String title;
Shape(String title) {
this.title = title;
}
В таске 16 class Circle - конструктор идет без title
Circle extends Shape {
private double radius;
Circle(double radius) {
this.radius = radius;
}
В итоге создала новый Shape для всех сабклассов без title.
Задуман этот title всем остальным сабклассам или это как пример абстракт класса ?
=> Lesson 8 level 4 all tasks

src/main/java/students/polina_ivashkevich/lesson_8/level_4/task_15/Shape.java
=> Lesson 8 level 4 task 15

src/main/java/students/jana_sergejenko/lesson_7/level_6/task_11/Palindrome.java, src/main/java/students/jana_sergejenko/lesson_7/level_6/task_11/PalindromeTest.java, src/main/java/students/jana_sergejenko/lesson_7/level_6/task_12/ArrayCopy.java, src/main/java/students/jana_sergejenko/lesson_7/level_6/task_12/ArrayCopyTest.java
=> lesson 7 level 6 task 12

src/main/java/students/jelena_kaverska/lesson_12/level_5_6_till_46/DescriptionValidationRule.java, src/main/java/students/jelena_kaverska/lesson_12/level_5_6_till_46/FieldValidationRule.java, src/main/java/students/jelena_kaverska/lesson_12/level_5_6_till_46/NameValidationRule.java, src/main/java/students/jelena_kaverska/lesson_12/level_5_6_till_46/PriceValidationRule.java, src/main/java/students/jelena_kaverska/lesson_12/level_5_6_till_46/Product.java, src/main/java/students/jelena_kaverska/lesson_12/level_5_6_till_46/ProductValidator.java, src/main/java/students/jelena_kaverska/lesson_12/level_5_6_till_46/ProductValidatorImpl.java, src/main/java/students/jelena_kaverska/lesson_12/level_5_6_till_46/ProductValidatorImplTest.java, src/main/java/students/jelena_kaverska/lesson_12/level_5_6_till_46/ValidationException.java
Заменила "не должно быть длиннее 2000 символов" на 300, поленилась искать такой текст :)
=> Lesson 12 level 5-6

src/main/java/students/jekaterina_aleksejeva/lesson_12/level_2/task_7/AccessDeniedException.java, src/main/java/students/jekaterina_aleksejeva/lesson_12/level_2/task_7/BankApi.java, src/main/java/students/jekaterina_aleksejeva/lesson_12/level_2/task_7/BankApiImpl.java, src/main/java/students/jekaterina_aleksejeva/lesson_12/level_2/task_7/BankApiImplTest.java, src/main/java/students/jekaterina_aleksejeva/lesson_12/level_2/task_7/BankClient.java, src/main/java/students/jekaterina_aleksejeva/lesson_12/level_2/task_7/Role.java, src/main/java/students/jekaterina_aleksejeva/lesson_12/level_2/task_7/UserCredentials.java
=> lesson12 level1 all tasks
